plugins/folder-manager/File.vala
plugins/folder-manager/FileView.vala

Uncomment this seemingly perfectly good move to trash item

Folder Manager: Move to Trash menuitem

---

plugins/folder-manager/FileItem.vala
plugins/folder-manager/Item.vala

Moving the `trash` method to `Item` as it will be shared by `FolderItem` too.

Cleanup context menu for FileItem

---

schemas/org.pantheon.scratch.gschema.xml
src/Dialogs/PreferencesDialog.vala
src/Services/Settings.vala
src/Widgets/SourceView.vala

Rip out those line numbers settings

---

schemas/org.pantheon.scratch.gschema.xml

Enable line highlight by default

---

.gitignore

Ignore temp files in gitignore

---

plugins/pastebin/pastebin_dialog.vala

* Tabs to spaces
* Space before parentheses
* Brackets for ifs

PasteBinDialog: code style

---

plugins/folder-manager/File.vala

Show hidden files in folder manager

---

src/Widgets/ToolBar.vala

* Update license header
* GObject-style construction
* Don't use ToolItems where possible
* DRY

Toolbar.vala: misc cleanups

---

src/Widgets/LoadingView.vala

* Update license
* no `this`
* Correct style class
* Grid not box

Clean up LoadingView.vala

---

src/Widgets/SourceView.vala

* Update license headers
* Remove obvious comments
* no `this`
* GObject-style
* convert `set_language` to property

Clean up SourceView.vala

---

src/Dialogs/PreferencesDialog.vala

* Update license header
* Move things to construct where possible
* Make use of `Object ()`
* Fix margins around content
* Place the close button in the dialog action area
* Remove an extra box

PreferencesDialog.vala: misc cleanup

---

src/MainWindow.vala

This isn't actually hooked up to anything

Remove unused restore tab action

---

src/Utils.vala

* Update license header
* Add whitespace for legibility
* cuddle else
* Connect signals at the end
* Only default to text file filter when opening

Utils.vala: clean up filechooser

---

src/Services/Document.vala
src/Widgets/DocumentView.vala
src/Widgets/SourceView.vala

Fixes #216 
* Duplicate text from original
* Save if autosave.

Duplicate document properly.

---

plugins/brackets-completion/brackets-completion.vala

Fixes #183 and fixes #151. EDIT: Also fixes #31 and fixes #215 now, thanks to @snowparrot :+1: 
I'm not 100% happy with this, I wish I could make into a single action - right now it takes two undo commands to revert the completion.
I'm open for input on how to make this better - it is my first time using Vala.

Brackets completion preserves selection

---

schemas/org.pantheon.scratch.gschema.xml

Default to draw spaces for selection

---

plugins/word-completion/completion-provider.vala
plugins/word-completion/engine.vala
plugins/word-completion/plugin.vala
src/Dialogs/PreferencesDialog.vala

Updates the Free Software Foundation address in license headers
Fixes https://bugs.launchpad.net/scratch/+bug/1653413

Update FSF address

---

src/Application.vala

* Update copyright header
* Add brackets
* remove an unnecessary comment

Application.vala: Update copyright header

---

plugins/contractor/contractor.vala
plugins/outline/OutlinePlugin.vala

Only the whitespace changes from #237

Misc whitespace cleanups

---

src/MainWindow.vala
src/Widgets/SplitView.vala

Just split view changes from #237

SplitView.vala: make show_welcome private

---

plugins/contractor/contractor.vala
plugins/outline/OutlinePlugin.vala
src/Services/Document.vala

Just the mimetype property changes from #237

Document.vala: replace get_mimetype with mimetype property

---

plugins/spell/spell.vala
src/CMakeLists.txt
src/MainWindow.vala
src/Widgets/FormatBar.vala
src/Widgets/HeaderBar.vala
src/Widgets/SearchBar.vala
src/Widgets/SourceView.vala

Created a new FormatBar widget to the headerbar

---

README.md

libvala >= 0.34

---

src/MainWindow.vala
src/Services/PluginManager.vala
src/Widgets/HeaderBar.vala

I need this before I can implement #296 
Looks like no plugins currently use the main menu hook so YAGNI

AppMenu is a popover now

---

plugins/strip-trailing-save/strip-trailing-save.vala

This might help with #305 , it definitely contains 100% less magic now. So we'll see.

Use a regular expression to strip trailing whitespace

---

data/io.elementary.code.appdata.xml.in.in

fixes bug: https://github.com/elementary/code/issues/315

Add screenshot to appdata

---

src/Dialogs/PreferencesDialog.vala

valign center settings switches

---

src/Services/Document.vala
src/Widgets/DocumentView.vala

Use a Granite.Widgets.AlertView instead of a Dialog to tell the user when a file is incompatible

---

README.md

To use "code" instead of "scratch"

Update weblate badge in README.md

---

plugins/outline/meson.build

Detect the libvala version

---

plugins/open-with/open-with.vala

Make open with plugin menuitem visible

---

data/io.elementary.code.appdata.xml.in

Fix #13 
also fix [The Flathub Package](https://github.com/flathub/flathub/issues/273)
since in launchpad don't list the fix or features that come with it. i only made a release tag with out that information

appdata: Add Release Tag with latest release of LP

---

meson.build
src/Dialogs/PreferencesDialog.vala
src/Services/Document.vala

gtksourceview: bump dependency to 3.18

---

src/FolderManager/FileItem.vala

Add Open In menu to files in sidebar

---

data/io.elementary.code.gschema.xml
data/io.elementary.code.plugins.spell.gschema.xml
data/io.elementary.code.plugins.terminal.gschema.xml
src/config.vala.in

Whitespace-only changes to adhere to the .editorconfig in #372

Fix whitespace

---

src/FolderManager/FileItem.vala

Add New Window to Open In menu in folder manager #371

---

src/FolderManager/FileItem.vala

Because HIG and dialogs and stuff

FileItem: Hide close button from App Chooser dialog

---

po/plugins/es.po
src/Widgets/FormatBar.vala

Accept colon in line number

---

src/Widgets/FormatBar.vala

Fixes #419 
It seems like the language selection dropdown was grabbing focus when switching between files. So, you could spam Ctrl+W to close tabs as long as they were all Vala files or all C files, etc... but as soon as a focused tab changed the current language, the dropdown grabbed focus.
The same was happening when opening new documents.

Prevent language dropdown grabbing focus

---

data/Application.css

Remove the margin from the SourceMap scrubber

---

plugins/brackets-completion/brackets-completion.vala

Fixes #344 
Fixes #309 
Fixes #308 
Most of these fixes were pretty interwoven, so it's all ended up in one diff.

Several improvements to bracket completion logic

---

plugins/brackets-completion/brackets-completion.vala

Auto indent bracket pairs

---

plugins/brackets-completion/brackets-completion.vala

Don't start quote completion when the previous char is alphanumeric

---

src/MainWindow.vala

Find next/previous shortcuts

---

src/FolderManager/FolderItem.vala

Allow empty folders in sidebar

---

debian/io.elementary.code.install

Deb packaging juno builder blocks font

---

src/Widgets/SearchBar.vala

Makes the minimum width of the window just a little smaller:

Use flowbox inside the search bar

---

src/Widgets/DocumentView.vala

Inline toolbar tabs based off selected style

---

src/FolderManager/FolderItem.vala

Fixes a hang I was seeing when renaming folders in a project folder after the git status stuff got merged recently. My bad.

Extra null checking in project folder code

---

plugins/editorconfig/editorconfig.vala

Check file exists before trying to parse editorconfig

---

data/io.elementary.code.gschema.xml
src/Dialogs/PreferencesDialog.vala
src/Services/Settings.vala
src/Widgets/SourceView.vala

Restore line wrap preference

---

src/Services/Document.vala

Document: string improvements

---

src/FolderManager/ProjectFolderItem.vala

Instead of using a function to pass back a menuitem, create a private class to do things in a more object-oriented way

ProjectFolderItem: Rewrite change branch submenu as a class

---

src/Application.vala

Fixes #680
Deal with null args after parsing

Fix null file warning dialog with new window from dock.

---

src/FolderManager/FolderItem.vala
src/FolderManager/ProjectFolderItem.vala

Resubmission of  #674 
Resubmitted this pull request because my original forked branch was deleted. The latest requested changes have been implemented.

Add "Open In" menu to the top-level project folder

---

src/Widgets/SearchBar.vala

SearchBar: Disable flowbox selection

---

data/io.elementary.code.appdata.xml.in

Some recent changes were not indicated in the appdata.

Update new release appdata for recent commits

---

data/io.elementary.code.appdata.xml.in
meson.build

Couple of handy features merged in March

Release 3.4.0

---

src/FolderManager/FolderItem.vala

Fix warning about unhandled error

FolderItem: Handler error when getting file child

---

data/io.elementary.code.appdata.xml.in
data/io.elementary.code.gschema.xml
src/MainWindow.vala

Remember whether sidebar is open

---

src/Widgets/Pane.vala

Pane: Add a label to open folder button

---

src/MainWindow.vala

Fixes #863
This should already be it, right?

Set window title to focused document

---

src/MainWindow.vala

Fix window positioning via saved state

---

po/POTFILES

POTFILES: Remove browser files

---

src/MainWindow.vala
src/Services/PluginManager.vala

Old:
```
+----------------------------------------------------------+
|         |                                                |
|         |                                                |
|         |                                                |
|         |                                                |
|         |                                                |
|         |                                                |
|         |                                                |
| sidebar |              content_stack                     |
|         |                                                |
|         |                                                |
|         |                                                |
|         | …
```

Add a footerbar and change bottombar on bottom of content_stack

---

plugins/outline/Vala/ValaSymbolOutline.vala

Use set_target_profile() instead of directly setting it.
Fixes #891

Fix build with Vala 0.50

---

io.elementary.code.yml

also, add universal-ctags, for c outiline.

Flatpak: update runtime and dependences

---

plugins/preserve-indent/preserve-indent.vala

Check that characters counted as indentation are whitespace

---

debian/control
debian/rules

It is now automatically handled by the packaging process.

Remove the -dbg package

---

src/Widgets/FormatBar.vala
src/Widgets/HeaderBar.vala

FormatBar: Remove custom styles

---

src/Dialogs/PreferencesDialog.vala

Update to be compatible with latest Greenfield

PreferencesDialog: Adjust margins and spacing

---

plugins/pastebin/pastebin_dialog.vala

PastebinDialog: Fix dialog margins, code style

---

src/Widgets/SourceView.vala

Improves the way multiple-lines are duplicated - now behaves like Geany.
If the selection includes multiple lines then *the whole* of the lines including the selection are duplicated and placed on a new line after the last line selected. This means it is no longer required to carefully select the whole of the lines to be duplicated and the duplicate is not appended to the end of the last line selected - which is not expected.
Also the original selection is now selected while the duplicated lines are not selected. This makes it easier to e.g. comment out the original lines before modifying the duplicate lines - this is useful for making experimental changes while keeping the original visible.
An unused (and badly named) property of SourceView is removed in passing

Better duplication of multiple lines

---

src/Widgets/Sidebar.vala

Fixes a regression causing the sidebar actionbar not to be displayed.

Fix regression due to c35a306f03e3ddef5c2d3c8dff4e69caaa78c667

---

src/Services/Document.vala

Document: changed message () to debug ()

---

src/Dialogs/GlobalSearchDialog.vala
src/FolderManager/ProjectFolderItem.vala

Fixes #1008 
Also rebases the dialog on Granite.MessageDialog, similar to the NewBranchDialog.

Fix empty and cancelled global search

---

src/Widgets/DocumentView.vala

DocumentView: Remove inline-toolbar

---

src/Widgets/DocumentView.vala

tab color wasn't being updated when style schemes change

DocumentView: fix tab color change

---

src/Widgets/ChooseProjectButton.vala

So that the popover will shrink to fit contents and max out at 350

ChooseProjectButton: use max_content_height for scrolled

---

src/Widgets/ChooseProjectButton.vala
src/Widgets/HeaderBar.vala

Instead of hard coding a margin, we can center align for the same effect

ChooseProjectButton: valign center

---

plugins/terminal/terminal.vala
src/FolderManager/ProjectFolderItem.vala
src/Services/Document.vala
src/Services/MonitoredRepository.vala

Fix spelling in some warnings (patch from fmneto)

---

README.md

README: bump granite dep

---

src/FolderManager/FolderItem.vala

Opens newly created file.

---

src/MainWindow.vala
src/Services/Document.vala
src/Services/TemplateManager.vala
src/Widgets/DocumentView.vala
src/Widgets/SearchBar.vala
src/Widgets/SourceView.vala

Found via `codespell -q 3 -S *.po,./po`

Fix various typos

---

src/FolderManager/File.vala

Fix #1077 
Right now this only forces code to show hidden files. No different styling is done.

Show hidden folders by default

---

src/Services/MonitoredRepository.vala

Untracked files aren't affected by branch changes, ignore thoses when checking for uncommitted changes.

MonitoredRepository: Allow Changing Branch with Untracked Files

---

src/Widgets/SearchBar.vala

Template string in Vala are not compatible with i18n.

SearchBar: Make the search count translatable

---

data/io.elementary.code.gschema.xml
src/Widgets/DocumentView.vala
src/Widgets/HeaderBar.vala
src/Widgets/SourceView.vala

Fixes #902 
Supersedes #1192
Could probably be dryer but does the thing

Add follow system style switch

---

src/MainWindow.vala
src/Widgets/HeaderBar.vala
src/Widgets/Sidebar.vala

Since we hide and show this with the project sidebar, put it in the sidebar

Put the ProjectChooserButton inside the sidebar

---

src/Application.vala
src/FolderManager/FileItem.vala
src/MainWindow.vala
src/Widgets/DocumentView.vala

Only restore documents for first window.

---

src/Services/GitManager.vala

Do not add duplicate project

---

src/SymbolPane/SymbolOutline.vala

Fixes #1263 
Just copied the corresponding code from DocumentView.

Make symbol outline aware of follow-system-style setting

---

src/Widgets/SearchBar.vala

Do not change document search results unexpectedly on focus in

---

src/MainWindow.vala

This makes it consistent with Files, Terminal and Web.
See also: https://github.com/elementary/terminal/pull/716.

Add ctrl + pageUp and pageDown for switching tabs

---

data/io.elementary.code.gschema.xml
src/Widgets/SearchBar.vala

We can sync the `active-id` property to the `nick` value since these are both strings

Simplify settings handling

---

data/code.metainfo.xml.in

Metainfo: set brand color to Latte 500

---

data/io.elementary.code.1
data/meson.build

Following similar PR for Terminal.  Debian install to be updated in other PR

Install man page with meson

---

src/Widgets/DocumentView.vala
src/Widgets/SourceView.vala

Silences some unnecessary terminal output.

Reduce terminal noise

---

data/io.elementary.code.1
src/Application.vala
src/MainWindow.vala
src/Services/PluginManager.vala

Towards addressing #1322 
A separate PR is required to remove the option from the man page,

Remove plugin set option

---

data/code.metainfo.xml.in

Update metainfo for latest merges.
Fix some incorrect issue links

Release 7.1.0 update metainfo

---

src/Widgets/SearchBar.vala

Fix logic for clearing search entry

---

data/io.elementary.code.gschema.xml
src/MainWindow.vala

GTK 4/Wayland prep. Can't set window position in Wayland

gschema: remove window position

---

src/MainWindow.vala

System theme change now fully respected while Code already running

---

src/Application.vala

Fixes "new-tab" command line option

---

src/Widgets/DocumentView.vala

Skip New Documents when disambiguating tabs

---

data/code.metainfo.xml.in

Update metainfo for release 7.2.0

---

src/Dialogs/PreferencesDialog.vala

PreferencesDialog: make resizable

---

src/FolderManager/FileItem.vala
src/FolderManager/FileView.vala
src/FolderManager/FolderItem.vala
src/FolderManager/ProjectFolderItem.vala
src/Utils.vala

Completes the "Replace Gtk.MenuItem with GLib.MenuModel" task in #1157

[GTK4 Prep] Create FileView Context Menu Items using GLib.MenuModel

---

src/MainWindow.vala

Remove code whose function has been absorbed into another function.

Lose unused function

---

plugins/brackets-completion/brackets-completion.vala

* Bump copyright header
* Explicit scope private variables and methods
* Fix weird line wrapping of arguments

BracketsCompletion: misc cleanup

---

data/io.elementary.code.desktop.in.in
data/io.elementary.code.gschema.xml
data/meson.build
meson.build
plugins/fuzzy-search/fuzzy-search-indexer.vala
plugins/fuzzy-search/fuzzy-search.vala
src/FolderManager/FileView.vala

Reverts elementary/code#1568
Merged into wrong repo! Intended for fork.

Revert "Install as different application"

---

src/FolderManager/ProjectFolderItem.vala

Remove trash item from project menu
