- src/MainWindow.vala
Reduce critical warnings on start up due to use the variable "app" in the construct block of MainWindow before it has been assigned.
Remove a further warning during construction of MainWindow caused by reference to a non-existent action.
> Fix window construct

- plugins/folder-manager/FolderItem.vala
There's no reason why this should be any different from the other methods.
> Set method accessibility to private to keep convention

- src/Widgets/SplitView.vala
- GObject style construction
- Remove this
- Move signals to the top
> Split view cleanups

- plugins/browser-preview/browser-preview.vala
- plugins/strip-trailing-save/strip-trailing-save.vala
- src/MainWindow.vala
- src/Widgets/SearchManager.vala
Fixes #146 by checking for possible null returned by MainWindow.get_current_document () in one place and takes the opportunity to add similar checks in other places where missing (even if null is unlikely).
> Fix #146 - Add checks for null current document where necessary

- plugins/pastebin/pastebin_dialog.vala
Fixes #158 
The final link seems to always say "this past has been removed" etc etc in both this branch and master, so I guess it's outside the scope of this fix :man_shrugging: 
* Use Gtk.Dialog instead of Granite.LightWindow
* GObject-style construction
* Grid to layout instead of nesting boxes
* Code style fixes
* HIG fixes
Before:
After:
> Pastebin plugin: rewrite as Gtk.Dialog

- src/MainWindow.vala
Fixes a styling bug in 3.22 where the sidebar has an extra frame
> Remove frame from sidebar notebook

- src/Widgets/SearchManager.vala
Saves us on having to put everything into tool items
Uses linked grids to group buttons
Pro/Con: window width now must fit all the searchbar widgets so the Go To Line entry can no longer be hidden in a smaller window. On the other hand, this actually takes up a lot less width so all the widgets can fit into a smaller window than before
Before:
After:
> Rewrite SearchManager as a Gtk.Grid

- plugins/word-completion/completion-provider.vala
- plugins/word-completion/engine.vala
- plugins/word-completion/plugin.vala
Fixes #184.
* Decreases minimum word length to 1.
* Removes the timeout to show completion window completely.
* Hides the "Word completion" header in the completion window.
> Sane defaults for word completion

- src/scratch-ui.xml
I was having quite a few issues with keyboard accelerators, after removing this line, they all magically went away.
I suspect it's because something was pointing at an action that no longer existed.
> Remove leftover RestoreTab action from UI file

- src/MainWindow.vala
* disambiguate between Gtk.Application and Scratch.Application so that it's clearer what we're actually setting in the object
While we're here:
* Make default title translatable and fix icon name
* code style
> Object disambiguate

- src/MainWindow.vala
- src/Widgets/SplitView.vala
- src/Widgets/ToolBar.vala
Adds a SimpleActionGroup and converts the app menu from using the deprecated Gtk.Action to GLib.action
> Convert app menu to use glib.action

- po/CMakeLists.txt
This file was renamed but cmake wasn't updated so pot generation fails
> Fix file name for pot generation

- src/Widgets/LoadingView.vala
This regression was introduced by #172. The loading view was centered before, but the change from `Gtk.Box` to `Gtk.Grid` affected the centering of the text and the spinner in the loading view.
> Fix regression with loading view centering

- src/Application.vala
If I want debug I can use `--debug`, otherwise this is excessive
> Don't default log level to debug

- src/Widgets/SearchManager.vala
When you search for something and it isn't found, that doesn't represent a failure in the code. It's still working as intended. Change this to "debug" level
> Change search result not found warning to debug

- src/Widgets/DocumentView.vala
Following the introduction of asynchronous loading, the order in which two handlers connected to the source_view focus-in-event signal was unexpectedly changed.  This had the unexpected effect of disabling the (now) second handler since the (now) first handler returns true.  To fix this handler that must be called second is connected using ```connect_after``` to ensure the correct order of calling.
> Ensure order of focus_in_event handlers (#228)

- plugins/contractor/contractor.vala
- plugins/outline/OutlinePlugin.vala
- src/MainWindow.vala
- src/Services/Document.vala
- src/Widgets/SplitView.vala
Fixes #232
* Handle filenames without scheme
* Make Document exists() cancellable
* Make Document mime_type a property to avoid re-querying
* Make SplitView solely control showing of Welcome view
* Add timeout to loading with option to continue
* DRY some dialog code
> Improve handling of problematic files

- src/Widgets/FormatBar.vala
Tabs:
* Put the auto-indent switch at the top like in prefs (So we don't have switch, spinbutton, switch)
Syntax Highlighting:
* Remove the sizegroup from the language selection so that Code can be tiled on notebook screens
* Use menuitem style class
* Add margin so selection rectangle doesn't bleed outside of the popover
Line number:
* Use view-continuous icon
* Use "." instead of ":" because that's what the compiler does
Misc
* Margins on popovers are 12 like in dialogs
* Remove unnecessary/unused/default properties
> Format bar ui changes

- src/MainWindow.vala
Sets the preferences dialog to modal before showing (fixes #254).
> Set Preferences dialog modal before showing (fixes #254)

- src/Application.vala
- src/Dialogs/PreferencesDialog.vala
Replaces custom header label class with Granite.HeaderLabel and removes the two deprecated granite.app properties
> Use Granite.HeaderLabel and remove deprecations

- src/Widgets/FormatBar.vala
Prevents:
_When the popover is outside the window, it's contents can't be clicked_
> Force popover position to bottom

- schemas/io.elementary.code.gschema.xml
I guess it turns out this isn't the default. We're setting it in the distro which is weird
> Set solarized light by default

- schemas/io.elementary.code.gschema.xml
Turns out we were setting this in the [distro](https://github.com/elementary/default-settings/pull/19) instead of here for some reason
> Highlight matching brackets by default

- src/MainWindow.vala
- src/Widgets/HeaderBar.vala
- src/Widgets/SourceView.vala
* Add Actions for zoom in and zoom out
* Use action accels instead of manually grabbing keys from gdk
* Remove the zoom default button from the headerbar and use the zoom controls widget from Terminal
> Use zoom controls as in Terminal

- src/Services/PluginManager.vala
- The `gjs` loader has been removed from upstream for many years
- Enabling two dynamic loaders (python and gjs) is broken in practice as they both leak references
- None of the plugins in-tree use it
(Sidenote it is probably time to move `python` to `python3`)
> Don't try to load gjs libpeas loader

- src/MainWindow.vala
https://elementary.io/docs/human-interface-guidelines#preference-dialogs
"Preference dialogs should be made Transient, but not Modal. When a user makes a change in a preference dialog, the change should be immediately visible in the UI. If the dialog is modal, the user may be blocked from seeing (and especially from interacting with) the change. This means they will have to close the dialog, evaluate the change, then possibly re-open the dialog."
> Don't set prefs dialog modal

- .travis.yml
- README.md
libdevhelp-dev isn't actually used anymore, so let's remove it from the readme and travis build
> Remove unnecessary devhelp dependency

- src/FolderManager/FileView.vala
- src/MainWindow.vala
Fixes #6 
When changing tab, select the item belonging to the new tab in the sidebar if it is visible (i.e. expanded) in the folder manager scroll view.
Otherwise, deselect the currently selected item in the folder manager, so it can be clicked again if necessary.
> On change tab, select file in sidebar if visible

- src/Widgets/SourceView.vala
There was some reference to a couple of source tags in the code. They weren't being added to the tag table and hence unusable. But these would be really useful for a language client implementation :wink: 
So, I've added them to the tag table and made a punt at changing the styling of one of them as I wasn't feeling the bright yellow background. The error tag is a nice red squiggly underline as you might expect. Green for warning?
**Before:**
**After:**
> Fix source tags

- .editorconfig
Since I've been dogfooding the editorconfig plugin, I figured it makes sense to ship one with this repo. This is mostly a reflection of the existing code, which is elementary-style, but with two-character indents for YML and XML (as it was in the repo). I can remove the special casing there if we want.
> Add initial editorconfig file

- src/FolderManager/FolderItem.vala
This temporary file made the file view flicker on file modification
> Don't add temporary GLib file

- src/FolderManager/FileItem.vala
Fixes a bug where misbehaving apps can display ridiculously large icons (cough Firefox)
> FileItem: Restrict app icon pixel size

- plugins/highlight-word-selection/highlight-word-selection.vala
There was quite a lot of wat in this plugin, for example:
```
src.deselected.disconnect (on_deselection);
src.deselected.connect (on_deselection);
src.selection_changed.disconnect (on_selection_changed);
src.selection_changed.connect (on_selection_changed);
```
It was also holding references to sourceviews and search contexts unnecessarily, we only need to keep track of the currently focused document.
> Simplify word highlight plugin

- src/Services/Document.vala
Fixes #427 
The modified flag on the text buffer is only a boolean to see if some changes happened since the last time the file was saved. So changing a file and then unchanging it still counts as changed.
If we want to track if the file is unsaved or not a bit more cleverly, we need to compare the content of the buffer to the content of the file when it was last saved.
> More accurately track save state of file

- plugins/pastebin/pastebin_dialog.vala
As per https://pastebin.com/faq
It could be that it should be "Pastebin.com", but in any event "PasteBin" is incorrect.
> Spelling "PasteBin" → "Pastebin"

- src/Widgets/SourceView.vala
Following a change to using native Gtk space drawing, white space within selection appeared differently (that is whether the line endings were drawn) depending on the settings.  With this PR, whitespace within a selection is always drawn with SourceTags.
Ideally a solution should be found for the SourceTags behaving differently from the SourceSpaceDrawer (maybe upstream?)
> Draw spaces in selection the same way if drawn at all.

- src/MainWindow.vala
Fixes #550 
Fixes #273 
When Code restores your last session and there's a file deleted, it creates a zero byte file,
If the file isn't exits anymore don't open it and refresh the view if there's no files opened (To restore the welcome screen)
> Fix empty files creation for previous opened files

- src/Widgets/DocumentView.vala
Fixes #515 
Prevents trying to restore documents that don't exist when closing a blank unsaved document.
> Don't add temporary files to tab restore

- src/Application.vala
Fixes #564 
Don't create the window before we check whether a window already exists or not and ignore null arguments.
> Fixes to the new window desktop action

- src/Dialogs/PreferencesDialog.vala
An example of something we could do for #425. Suggestions welcome.
> Try an info icon for smart cut/copy

- plugins/editorconfig/meson.build
`compiler.find_library` expects the `lib_name` without `lib` prefix.
> Fix finding editorconfig

- src/FolderManager/ProjectFolderItem.vala
* based on the work of Marcelo de Andrade <marceloga1@al.insper.edu.br>
* Catch GLib.Errors
* Null checks
Further work or PRs are advisable to, for example, warn if there are uncommitted changes in the current branch before changing branch and give options to deal with the situation.
> Implement change branch context menu item.

- src/MainWindow.vala
Fixes #619 
The cause was not precisely identified but is related to a race between realizing the widgets and hooking the plugins.  This is avoided by not hooking plugins until the realize signal is received.
> Fix crash on startup under some circumstances

- src/MainWindow.vala
- src/Services/Document.vala
- src/Utils.vala
Supersedes #640 
Fixes #639 
This util is only used twice so this seems like an unnecessary over abstraction. It's simpler and clearer to just make two dialogs.
Fwiw, this solution adds 2 lines as opposed to #640 which adds 8
> Utils: Remove filechooser util

- src/Services/Document.vala
Requires string changes since the "last 4 seconds" bit doesn't apply to unsaved temporary files
> Document: Rewrite unsaved changes warning as Granite.MessageDialog

- src/Application.vala
Separates title and body so we can format things correctly
> Application: Rewrite error dialog as Granite.MessageDialog

- src/Widgets/SplitView.vala
Using "Remove Current View" from the AppMenu was not working. This resolves that. Previously the code was using `get_focus_child ()` on `SplitView`, but as soon as you click on AppMenu the focus is lost. Using `current_view` instead works. Resolves #224.
> Remove Current View fixed

- src/MainWindow.vala
~Intended to fix #627. However, Code just segfaults instead… :expressionless:~
Fixes #627
> Add equal as zoom key

- src/Application.vala
Fixes #488
To test this PR, specify some language like this:
```
LANGUAGE=ja_JP io.elementary.code --help
```
```bash
ryo@ryo-pc:~/Projects$ LANGUAGE=ja_JP io.elementary.code --help
用法:
io.elementary.code [OPTION…] File
ヘルプのオプション:
-h, --help                                                                                                                                                                                                                                                                                                                                                                                                                                                          ヘルプのオプションを表示する
--help-all …
```
> Fix help info is not displayed correctly other than in en_US

- src/FolderManager/File.vala
- src/FolderManager/FolderItem.vala
> Now temporary files will not be displayed in the sidebar

- src/FolderManager/ProjectFolderItem.vala
Fixes #660 
Git branch submenu is set insensitive if there is only a single branch instead of showing an empty menu.
> Git branch submenu is only sensitive if there is more than 1 branch.

- src/Application.vala
Fixes #688 
We had some overly complicated leftover ways of trying to resolve relative paths from the command line and then passing them to the already running "remote" instance.
If we use the `ApplicationCommandLine` object, we can use that to resolve the relative paths for us and create the `File` object.
> Use ApplicationCommandLine to resolve relative paths

- README.md
(Meson did not detect `libzeitgeist` unless I had installed `libzeitgeist-2.0-dev`).
> Amend README with proper dependency name

- src/Widgets/SearchBar.vala
It looks like this fixes #708 
https://github.com/midori-browser/core/blob/34e938e2abf239df658bec91b6d8e708f5177f7a/core/urlbar.vala#L89
> SearchBar: Fix shift+enter

- src/Widgets/SearchBar.vala
Uses `dialog-error-symbolic` icon to indicate the search failed. I have also used vala-lint on the `SearchBar.vala` file I modified.
This is my second PR into an open source project, so feedback is greatly appreciated!
fixes #206
> Change Primary Search Entry Icon on Failure

- src/FolderManager/File.vala
- src/FolderManager/FolderItem.vala
- src/FolderManager/Item.vala
Fixes #213 
An alternative to #650, which should be less prone to race conditions.  The filename to be created is entered *before* any file is created using a temporary renaming item.  To match Files behaviour, if <Esc> is pressed (or a blank name entered) then a file with the default name is created rather than cancelling the file creation.
It proved necessary to poll the SourceList to determine when editing finishes because cancelling the editing does not generate any signal and we need to remove the temporary item in either case.
If this were fixed in Granite then a simplification here would be possible.
> FolderManager: Rename before create new file

- src/Widgets/Pane.vala
* Use actionbar to save us a few lines with `pack_end`
* Use `view-more-symbolic` for menubutton icon to be consistent with the icon elsewhere
* No ellipses for a tooltip that doesn't spawn a new window or view
* "Open" project folder instead of "Add" since we're not creating a new folder
* Tooltips are sentence case
> Pane: Use actionbar and adjust tooltips

- data/io.elementary.code.appdata.xml.in
- src/FolderManager/FolderItem.vala
Fixes #408 
When clicking on a folder it now expands/collapses instead of being selected.  Note that this simple solution does not allow the folder to be selected with a modified click should that be desired.  If that is wanted then overriding the button press or release handler would be needed.
> Make sidebar folders non selectable

- data/io.elementary.code.gschema.xml
- src/MainWindow.vala
For some reason we had hardcoded new windows to spawn at some arbitrary coordinates. This makes it so new windows will spawn centered (as dictated by gala)
> MainWindow: Center new windows

- src/Dialogs/PreferencesDialog.vala
> PreferencesDialog: Fix font switch is not valigned

- debian/control
Kind of a random thing, but I was playing around with `apt show` and ended up doing `apt show io.elementary.code` and saw that the description still reads "Scratch."
Since elementary Scratch has been renamed to elementary Code, I believe it would be a good idea to reflect this in the debian packaging description. Let me know if I am wrong about this or need to change anything!
> Scratch to Code in debian/control

- data/io.elementary.code.appdata.xml.in
- data/io.elementary.code.gschema.xml
- src/Application.vala
- src/MainWindow.vala
- src/Services/Settings.vala
Lockdown has led me to play with elementary and vala and a stab at one of the Bitesize issues
This may be utter nonsense but it seems to work for me so far, I'm not sure what to do about migrating an existing schema though?
Any feedback appreciated
> Use a single gsetting key for window coords/size (#768)

- data/io.elementary.code.appdata.xml.in
- src/Widgets/SourceView.vala
Fixes #799.
- Assumes we want at least three lines visible at all times (not configurable)
- Always on (not configurable)
- Throttled for performance (noticeably lags on resize without a timeout)
> SourceView: Scroll past end

- data/io.elementary.code.appdata.xml.in
- plugins/spell/spell.vala
Fixes #234. If we want to add more languages here, this might not be the best approach. But it seemed the least invasive.
> Spell: Enable plugin for md files

- src/Application.vala
We shouldn't need to do this since we're a Gtk.Application
> Application: Remove unnecessary Intl

- src/FolderManager/FileView.vala
I was seeing some issues where changing tab would sometimes work for a second and then switch back to the original tab.  Let's disconnect the `item_selected` signals in the Folder Manager when we're manually changing the selection so we don't get into some weird loop.
> Disconnect selected signals on tab change

- src/Widgets/HeaderBar.vala
- src/Widgets/SourceView.vala
`get_last_window ()` can and does return `null` when Code is starting up. Make sure we check that so we don't end up with fatal errors about this on startup.
> Null checks for get_last_window

- src/Application.vala
Having this here prevents `G_MESSAGES_DEBUG=all` from working, which is how we do things these days.
> Remove Granite.Services.Logger

- plugins/pastebin/pastebin.vala
- plugins/pastebin/pastebin_dialog.vala
- po/fr.po
- src/Widgets/FormatBar.vala
This fixes all of the issues mentioned in #871, removes one warning from #773 and improves the overall aesthetics of this plugin.
Before:
After:
I also adjusted some of the translatable texts in the code and I am not sure whether there is anything else needed there to make them available for translation.
Fixes #871
> Fix issues with the Pastebin plugin

- data/io.elementary.code.appdata.xml.in
- src/MainWindow.vala
- src/Widgets/DocumentView.vala
Fixes #841 : add shortcuts for next/previous documents. Also refactored `DocumentView.next/previous_document` to cycle opened documents.
> Ctrl+Tab for next document and Ctrl+Shift+Tab for previous one

- plugins/terminal/terminal.vala
- plugins/word-completion/completion-provider.vala
Fixes most compile warnings arising from plugins
Something weird is happening with `Vte.Terminal.spawn_async ()` - the Vala compiler is producing code that fails the C compiler for some reason so the deprecated `Vte.Terminal.spawn_sync ()` will be addressed in a later PR.
> Fix plugins compile warnings

- src/Widgets/DocumentView.vala
The `document-change` signal is being currently emitted twice on every tab switch as it is emitted both in the tab-switch handler and when the document is focussed.  As this signal is propagated to all the plugins and triggers many other activities this is not desirable.
> Stop document_change signal being emitted twice after tab switch.

- src/Application.vala
Fixes #689 
Supersedes #811 
This makes the option parsing much more compliant with the GLib recommended best practices and removes a lot of the manual parsing and error checking of arguments.
We already have error views per-tab (instead of one dialog for each file) when something fails to open, so let's use those.
> Simplify cmdline option handling

- src/Widgets/FormatBar.vala
* Fix margins around searchbar
* Remove extra margin in radiobuttons
* Use menuitem element name instead of css style
* Proper GObject style
* Other code style
> FormatBar: fix margin in lang popover

- src/FolderManager/ProjectFolderItem.vala
Try to keep the order of items consistent with the folder items in the sidebar and with Files
Before:
After:
> ProjectFolderItem: Organize menu and add separators

- src/FolderManager/FileView.vala
Currently if you have a long list of projects in the sidebar and you try and open one that's already open, nothing happens (other than a warning in the terminal). How about we expand that already open folder so you can see where it is easier?
> Expand folder when opening an already open project

- src/Widgets/SearchBar.vala
Fixes that really annoying search issue where if you re-focus the document it forgets what you were searching for. Might need some UX input as to whether this behaviour of keeping the search active until you delete it or close the search bar is desirable.
Fixes #528 
Fixes #692 
Fixes #812
> SearchBar: Refresh search on document focus change

- data/io.elementary.code.gschema.xml
- src/Widgets/HeaderBar.vala
We were incorrectly checking for `high-contrast` as a color scheme name in the switch statement, when it should have actually been `classic`; the fact that it was a group of radio buttons meant the mismatch selected the first radio button which just happened to be the right one, but this makes it more explicit in a couple of ways:
- Adds and uses consts for color scheme names so we can't mismatch them anymore
- Adds a hidden `color_button_none` that's never attached
- Defaults to selecting `color_button_none` when the switch statement doesn't have a match so we don't select the wrong color button e.g. if someone manually edits the GSettings
> HeaderBar: Correctly load color button states

- data/io.elementary.code.gschema.xml
There were just a couple of spots using inconsistent newlines and four-space indentation instead of two.
> GSchema: Correct whitespace

- src/MainWindow.vala
Fixes `gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkNotebook` critical errors on startup.
> Suppress criticals on startup

- debian/control
We need it to provide the .its files for translating the policy file.
> Add policykit-1 as build dependency

- src/Dialogs/GlobalSearchDialog.vala
* Only one grid
* Remove the "search for" label, since it seems fairly obvious what to do with the entry
* Use the semantically correct icon name
* typographical quotes
> Use fewer grids

- src/Services/GitManager.vala
Since it sounds like we expected this error when there is no git repo, move it to debug to avoid log noise
> GitManager: debug on error

- .github/workflows/ci.yml
Sorry for not notice this before, this should make the ci runnable again.
> CI: Fix YAML Syntax

- src/Widgets/ChooseProjectButton.vala
Fixes the animation when opening
> ChooseProjectButton: subclass menubutton

- src/MainWindow.vala
- src/Services/GitManager.vala
- src/Widgets/ChooseProjectButton.vala
- src/Widgets/HeaderBar.vala
Using GitManager as source of truth for the active project saves a useful number of lines and increases clarity.
- We may need a "ProjectManager" class as a controller for project objects in the wider sense (not just git repository objects).? #940  goes down this route. In which vase the active project should be controlled there and there are further simplifications possible in other classes.
> GitManager: source of truth for active_project_path

- src/Widgets/ChooseProjectButton.vala
It looks like this `selected` property is a duplicate of `active` but it exists only as a setter to workaround toggling the radiobutton.
Instead, we can use `active` for the setter, but change the signal handling of the radiobutton to `button_release_event` so that `activate ()` is only triggered when the button is actually activated by the user
> ChooseProjectButton: simplify ProjectRow click handling

- src/FolderManager/FileView.vala
- src/Services/GitManager.vala
Fix global search shortcut by allowing non-git projects in the chooser.
Throw a Gdk.beep if trying to use the new branch shortcut in a non-git project instead of crashing
> Allow non-git projects to fix global search

- src/FolderManager/ProjectFolderItem.vala
* Do not limit depth of recursion to 1
* Suppress terminal warning
Should not artificially limit the search depth to one - instead we should deal with possibly huge search scope and consequent interface blocking by making search asynchronous and providing a cancellation ability (for future PR).
> Do not cripple non-git folder search

- src/Application.vala
- src/MainWindow.vala
- src/Widgets/DocumentView.vala
This stops critical warnings like:
`(io.elementary.code:100977): Gtk-CRITICAL **: 13:21:33.248: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkNotebook`
when restoring documents at startup.
> Avoid size allocation warnings when restoring first docs

- src/MainWindow.vala
- src/Widgets/DocumentView.vala
There's only two places that we use `if_empty ()` and both of them only use it to signal `empty ()`, so might as well make `if_empty ()` do the thing
* Renamed `if_empty ()` to `request_placeholder_if_empty ()`, which is admittedly a bit verbose. Open to suggestions
* Renamed `empty ()` to `request_placeholder ()`, which is what this signal really does (for the most part)
* Made `request_placeholder_if_empty ()` signal `request_placeholder ()` so that we don't repeat ourselves
> DocumentView: simplify empty check

- src/Services/MonitoredRepository.vala
- src/Widgets/SourceGutterRenderer.vala
- src/Widgets/SourceView.vala
This PR attempts to get colors defined in the current or fallback SourceStyleScheme for ids "diff:added-line" etc otherwise use hard-coded colors.
Unfortunately of the three styles built into Code, only "classic" contains the relevant style ids and none contain a style explicitly for unchanged lines that replace lines that have been deleted, so the gutter colors do not currently actually change when the style is changed.
Not sure whether it is worth using a fallback SourceStyleScheme or should just immediately fallback to hard-coded colors.
> Get diff gutter colors from SourceStyleScheme if possible

- data/Application.css
- src/Widgets/HeaderBar.vala
Based on some work David started in #434 
This styles (and tooltips) color buttons from theme data instead of hardcoding it. There's been some work in the stylesheet to make color buttons work without a ton of custom CSS
This doesn't attempt to make the color buttons customizable, but it's a step in that direction
> Style color buttons from theme data

- src/MainWindow.vala
Fixes #1065
Emit placeholder_request signal in Idle loop when inside restore docs signal handler.
Possibly an obscure side effect of #1060
> Ensure Welcome buttons work when shown at start up

- src/Widgets/DocumentView.vala
Fix #1095 
There's still some strange situations where the new window has the same file opened twice, but at least it does not crash anymore. I'll try finding a reproducible test case later.
> Fix crash when creating new window from tab drop

- src/Widgets/ChooseProjectButton.vala
Fix #1075 . When a project is closed check if it is the currently active project (as selected in ChooseProjectButton) and resets active project to no active project state.
> Update ChooseProjectButton when a project is closed.

- src/Dialogs/GlobalSearchDialog.vala
- src/FolderManager/ProjectFolderItem.vala
Fixes #1127
We can't `get_toplevel ()` from `ProjectFolderItem` so it passes null. We can instead get the active window from Gtk.Application
> GlobalSearchDialog: set active_window as transient parent

- src/Services/Document.vala
This was the only location where the Gtk.FileChooserNative wasn't created with a parent window, fixes https://github.com/elementary/files/pull/1899#issuecomment-973996508
> Document: Set Filechooser Dialog as Transient for Main Window

- src/MainWindow.vala
Resolves #863 
Multitasking uses the window title for the title shown in the multitasking view, not the toolbar title as we had set. This changes that assignment so we update the window title when we move between documents.
> 863: Set window title to title of currently focused document.

- src/Widgets/SearchBar.vala
Add Regex Support for the search bar #533 
The PR adds some additional changes to the search bar.
- Regex Tool Button: When enabled, the _Find_ input accepts regular expressions, the **replace input doesnt** (The button toggles the `regex_enabled` property of the `Gtk.SourceSearchContext`
- Refresh search occurences on changed text: Connected to the `Gtk.TextBuffer.changed` signal to refresh the number of occurences, once the document text changes. This was only done when he `SourceView` got focused again
- Correct display of the occurence navigation arrows: on the last match, if cyclic search is enabled, the "Next" arrow is sensitive (and the "Previous" arrow on the first match) 
- Reenable replace actions on _Undo_: If a replace action is reverted, the replace (all) buttons would be …
> Search-bar enhancements (Regex Support)

- src/Widgets/SearchBar.vala
Fixes #1173 
Check null search_context before using; 
Cancel search occurence label update before changing context or textview
This PR should not change any functionality.
> Fix occasional crash in SearchBar

- src/Widgets/DocumentView.vala
Fixes #1176 
There's a race condition here due to the `Idle.add`. Documents can be restored from saved state, one of which will have `focus == true`. At the same time, we could have started Code with an argument to open another document (i.e. "Open With" from Files), this will also have `focus == true`.
So instead of focusing all documents that have `focus == true` in an unpredictable manner due to the `Idle.add`, only focus the one that's set to `current_document` above in the synchronous code.
> Only focus the current document on open

- data/io.elementary.code.appdata.xml.in
Noticed that none of the recent changes to Code have been captured in the AppData yet. There's some good stuff in here, so we should probably prepare a release soon.
This includes a line for #1177 which hasn't been merged yet, so ideally would be merged after that.
> Update appdata with recent changes

- src/Utils.vala
`slice()` was removing the last character of the path.
> replace_home_with_tilde: use `substring()` to remove home directory

- .gitignore
If Flatpak build files are generated in the root of the source then they get searched in a global search slowing it greatly and resulting in warnings when committing changes.  To avoid this they are added to the `.gitignore` file.
> Git ignore flatpak build files

- src/FolderManager/ProjectFolderItem.vala
- src/Widgets/SourceGutterRenderer.vala
The properties `ProjectFolderItem.top_level_path` and `SourceGutterRenderer.workdir_path` are never used.
> Remove unused properties

- src/Widgets/SourceView.vala
Fixes #1244 
Showing the percentage zoom while Control-Scroll zooming will be left for a separate PR as that is a UI change which may not be desired.
> Make Control-Scroll zooming controllable

- src/MainWindow.vala
- src/Services/Document.vala
- src/Services/GitManager.vala
- src/Widgets/ChooseProjectButton.vala
Fixes startup warnings in terminal
Still a close down warning that I have not been able to track down yet.
One warning required reworking the ChooseProject Button (cannot have both a bound model and a filter func on a listbox).
> Fix startup warnings

- src/FolderManager/FileView.vala
- src/FolderManager/ProjectFolderItem.vala
- src/Services/GitManager.vala
Since commit 9e9c3ef5d9e8799fbe2b5aab3aec47e2d83ca282 the global search action is disabled at startup because the `active_project_path` has not been set in the GitManager (pre-existing hidden issue).
This PR ensures that at startup an active project path is set so long as at least one project folder is present in the sidebar.  To ensure this, it was necessary for some functions to be changed to handle non-git folders properly.  These now appear in the ProjectChooserButton as well as git projects.
> Ensure active project at startup (include non-git folders)

- src/Services/Document.vala
Fixes #1261 
Restores the old location of a document when "Save As" operation fails.  This avoids the odd behaviour and possible data loss observed in the issue.
The "save_as" function now returns the correct value if the save operation fails (i.e. whether or not the file was actually saved).
> Handle saving to unwritable location better to avoid data loss

- data/io.elementary.code.desktop.in.in
- data/meson.build
- meson.build
- meson_options.txt
- src/Application.vala
- src/MainWindow.vala
- src/Widgets/HeaderBar.vala
- src/config.vala.in
- src/meson.build
Another speculative development aid.
This makes it discoverable which branch of Code is running if not master.  This can be useful when switching between master and the development branch for comparison and there is no other visual cue.  Also for knowing which branch you are currently dogfooding.
For simplicity and compatibility with other apps, the branch is exposed in the window title.
In order for the modified window title to be shown, the project needs to be built with the meson option `-Ddevelopment=true`.
> Show running branch if not master

- src/MainWindow.vala
- src/Widgets/SourceView.vala
Fixes #1270 
Transfer responsibility for reacting to "follow-system-style" setting to MainWindow so works when no documents.
> Fix styling when no documents

- src/Widgets/SearchBar.vala
Fixes #1266 
- Combine and simplify the 3 functions for updating search widgets to ensure consistency
- "Replace all" remains sensitive if there are any outstanding matches after first use
- "Replace" becomes insensitive if there is no focused match (even if matches exist) because Cyclic Search is off.
> Ensure Replace button (and other search widget) states are mutually consistent 

- data/io.elementary.code.gschema.xml
- src/Widgets/SearchBar.vala
Adds case sensitive mode, whole word search and regex search settings to the existing cyclic search setting to the "io.elementary.code.settings" schema so that these settings now also persist.
> Persist search settings

- src/Services/Document.vala
Fixes #1316
The issue was caused by the `focus-in-event` handler checking the file status before the duplicate has been created resulting in a further error dialog. This was fixed by putting the document in a `working` state while duplicate creation is in progress and ignoring focus in events in that state.  The file status is checked after save-as completes instead.
> Fix creating duplicates of unwritable files

- src/Widgets/FormatBar.vala
Fixes #1341 
In order to match compiler error output.
> FormatBar: Show column number not buffer offset

- src/Services/Document.vala
Fixes #1208 
It was noticed that everytime a document was closed or opened `strip-trailing-whitespace` was called multiple times (at least once for each open document).  This was caused by `restore-settings` being called unnecessarily because the key `open-files` changed and causing a lot of unnecessary work if a lot of documents are open.
This PR uses more specific handlers for the `show-mini-map` and `strip-trailing -on-save` keys only.
> Handle only relevant settings key changes

- src/Services/Document.vala
Since recent changes to external change handling it was noticed that spurious warnings of external changes were produced while editing.  This was traced to file status checking not completing before autosaving commenced because source loading is asynchronous.
This PR makes sure file status checking completes before saving starts when autosaving.
> Fix spurious external change warnings

- src/FolderManager/FileView.vala
- src/FolderManager/ProjectFolderItem.vala
> Fix-folder-search-filtering-1198

- src/FolderManager/FolderItem.vala
- src/FolderManager/ProjectFolderItem.vala
Fixes #818 
Renaming a project folder externally results in it receiving a DELETED file monitor event and there is no obvious way of knowing what the new name is so the only solution is to close it.
> Close root folder if externally deleted or renamed

- data/io.elementary.code.gschema.xml
- src/Services/Document.vala
- src/Widgets/DocumentView.vala
Fixes #1329 
- Add a new saved-state key `outline-width`
- Bind to corresponding property of DocumentView
- Keep Documents, DocumentView and saved-state settings in sync
A consequence of the PR having a single setting is that the outline pane width is always the same in all documents rather than individually adjustable but this is unlikely to be an issue.
> Synchronise and save symbol outline width.

- plugins/fuzzy-search/fuzzy-search-popover.vala
- Point popover to the folder manager since that is where it is searching
- Show folder manager temporarily if it is hidden when popover is shown (else points to random position)
I am not sure about this one.  The issue I am trying to address is where the popover should point if the foldermanager or searchbar is hidden. Feel free to reject.
> Associate popover with foldermanager

- plugins/fuzzy-search/fuzzy-finder.vala
- plugins/fuzzy-search/fuzzy-search-popover.vala
- Prioritise sequential matches at start of filename
- Match folder exactly if specified
- Do not split matched parts across directory separator in path
With this PR if you enter something like "src/c" it will find files starting c (or containing) in or below the "src" folder.  
"src/w" will also match all files in "src/Widgets/" and any other folder containing "w" and any file below "src" containing "w" which I am not sure is a desirable behaviour but that can be fixed separately if not.
Multiple directory separators are now accepted but note that only the first folder must be an exact match.  So "src/w/s"
Will match all filenames containing "s" in foldername containing "w" below "src" .
"cool" in "code/po/lu.po" is not now matched
> Make fuzzy-find less fuzzy in some respects

- src/MainWindow.vala
- src/Widgets/ChooseProjectButton.vala
Fixes #1413 
Although the list box is in SINGLE selection mode, the radio buttons in the project rows are not affected by this so have to be explicitly unchecked when a new active project is chosen.
This PR makes the GitManager the source of truth regarding the active_project_path.  Some public access is removed. It also simplifies the ProjectRows and makes sure they remain grouped even when projects are removed and are re-added.
> ChooseProjectButton: Deactivate all project rows before selecting new active project

- data/io.elementary.code.gschema.xml
- src/Dialogs/PreferencesDialog.vala
- src/FolderManager/ProjectFolderItem.vala
- src/MainWindow.vala
- src/Services/GitManager.vala
This PR allows the setting of a global default build directory (relative to the root of projects) so that when the path of the terminal pane is changed by manually selecting the active project or using the ProjectFolderItem context menu, the desired build location within the project is automatically used.
> [Feature] Implement default build directory setting

- src/FolderManager/ProjectFolderItem.vala
Fixes #574 
Makes current branch visible without excessive sidebar width when both project and branch have long names
> Put branch name on separate line

- debian/control
Browser preview plugin was dropped in https://github.com/elementary/code/pull/868
> Control: Drop webkit from build deps

- src/Application.vala
Other options are localized, so I guess we should localized this string too for consistency.
Also use UPPER_SNAKE_CASE for parameters which is commonly used case in other commands like cp, tar, etc.
> Application: Localize go-to option

- src/Services/Document.vala
Fixes #1412 
Adapt to changed mime type for zero size files.
> Allow new documents (zero size files) to open.

- src/Widgets/Terminal.vala
Replaces usage of Gtk.MenuItem with GLib.MenuModel in the Terminal widget as #1157
> Define terminal menu items using GLib.MenuModel

- src/Widgets/SourceView.vala
When the value of `offset` in the SourceView widget's `go_to_line` method is less than 0, use `0` as the character position instead of `offset` to prevent cursor being moved to the line before the intended line number to go to.
> Fix "go to line" behaviour when column number is not explicitly set

- src/Dialogs/PreferencesDialog.vala
We use "whitespace" here, so this should maybe be the same? Or maybe that one should be changed? Or maybe they should both have a hyphen? :laughing: 
But I think they should at least be consistent.
https://github.com/elementary/code/blob/a03ec88be58ec125d6e009799fd522c63a47f344/src/Dialogs/PreferencesDialog.vala#L25
> PreferencesDialog: make whitespace strings consistent

- src/FolderManager/FileItem.vala
- src/MainWindow.vala
Part of of "Replace Gtk.MenuItem with GLib.MenuModel" task in https://github.com/elementary/code/issues/1157
After this, the none of menu items in FileView context menus will be activated using the `activate` signal. The switch to GLib.MenuModel will be simple after this.
> [GTK4 Prep] Use actions for New Window menu item in FileItem

- src/Utils.vala
Hi!
I think this fixes https://github.com/elementary/code/issues/1440. As mentioned there, a way to reproduce is to open the folders `/usr` and `$HOME/usr`. In this case, the issue is not so much that the two folders and their ancestors have the same names, but that `find_unique_path` does not handle recursion up to the root.
This is my first contribution to a Vala project, ever. In particular, I don't know how to call a code formatter or how to write unit tests (which would make a lot of sense with the present issue). If you show me how, I will gladly update my PR.
> Fix the app crashing when two folders and their ancestors have the same names

- src/Services/CommentToggler.vala
Fixes #1466
- Ignore empty (all whitespace) lines
- Only add/remove end tag if start tag as been added/removed
The existing code could do with some simplifying and commenting but that is left for another PR.
> Fix block comment toggling for empty lines

- src/FolderManager/FileView.vala
- src/Services/Document.vala
Fix #1281 
Completes #1461 
Emulates GEdit behaviour when *not* Flatpak, except that the file is added on save not immediately on opening.  So the file is not added if it is opened and closed without saving or renaming. This can be modified if required.
> Add saved and renamed docs to RecentManager

- src/Utils.vala
Rather than listing applicable apps in indeterminate order, they are shown in locale alphabetical order.
> Sort Apps for "Open in ..."

- plugins/word-completion/meson.build
- plugins/word-completion/prefix-tree-node.vala
- plugins/word-completion/prefix-tree.vala
Towards #1491 
Little value by itself but in order to implement dynamic updating of the tree when text is deleted it is necessary to make this class more complex (e.g. keeps track of number of occurrences of each word) and a lot of code in PrefixTree can be moved here.
> Rework word completion: Split out PrefixNode class

- po/POTFILES
- src/Dialogs/OverwriteUncommittedConfirmationDialog.vala
- src/FolderManager/ProjectFolderItem.vala
- src/Services/MonitoredRepository.vala
- src/meson.build
Fixes #1521 
Split out from #1516 
- Before checking out a branch determine whether there are any uncommitted changes in the current branch
- Obtain the diff in text form
- Show a confirmation dialog with the diff text as error details
> Confirm overwriting uncommitted changes on branch change

- data/icons/48/open-project.svg
- data/io.elementary.code.gresource.xml
- src/Widgets/WelcomeView.vala
folder-saved-search doesn't exist in the fd.o spec, so gresource our own icon
> WelcomeView: use resourced icon for project

- src/Services/Document.vala
- src/Widgets/DocumentView.vala
Fixes #1536 
For empty temporary documents, async code intended to be called once for a closing document was being called twice. For obscure reasons this lead to the `n_pages` property of `Hdy.TabView` becoming different from the actual number of pages and hence the issue.
An existing private flag was made public and used to prevent the responsible code being called twice.
> Fix closing an empty temporary document

- src/Dialogs/CloseProjectsConfirmationDialog.vala
The previous code calls normal gettext method `_()` in the method `ngettext()`, which results the singular and plural strings are recognized as different texts instead of singular/plural form of one text.
> CloseProjectsConfirmationDialog: Correct ngettext format

- src/Dialogs/OverwriteUncommittedConfirmationDialog.vala
- Replace dialog-stop icon name that actually does not exist
- Replace a trailing space with a period
- Follow the button order that we use in other dialogs
> OverwriteUncommittedConfirmationDialog: Correct icon name and buttons order

- README.md
> README: Replace libsoup2.4-dev with libsoup-3.0-dev

- src/Services/PluginManager.vala
* Explicitly declare scope of private variables and methods
* extension set can be private to the construct block
* Fix code style of property accessors. `get`, then `set`. only declare scope if it overrides the property scope
* Signals don't need a comment, they declare themselves to be signals
* Object call on one line since it only has one argument
> PluginsManager: cleanups

- src/Services/PluginManager.vala
> PluginManager: bump license header

- src/Dialogs/CloneRepositoryDialog.vala
Simplify things a bit:
* Set dialog modal. Happy to revert if it was intentional, but seems like we wouldn't want to spawn a bunch of the same dialog?
* Simplify placeholder text a big. `example.com` is reserved for examples
* Remove the folder image. This is a bit misleading as it looks like it's going to reflect the icon associated with the location but it always looks like the downloads folder
* Change the ellipsis icon to folder-open to better communicate what will happen when it's pressed
* Remove redundant headers
* Reduce margins
* Change from "URI" to "URL" since we specifically expect an http URL and not any resource location
* "Parent folder of clone" seems clunky. GNOME Builder just uses "Location" and that seems fine to me :woman_shrugging:
> CloneRepositoryDialog: design tweaks

- src/SymbolPane/SymbolOutline.vala
- src/SymbolPane/Vala/ValaSymbolOutline.vala
It seems that Document function `get_slice ()` is not thread-safe (?) and sometimes causes a crash during startup. An occasional crash during use was also noticed that may be due to reparsing the document.
This function is used for constructing the symbol pane items' tooltips. 
Calling this function on each item *after* the tree is constructed rather than during the construction of each item seems to fix the crash but some testing is needed to assure this as the exact reason has not been determined.
Needs to be tested and merged before next release can take place.
> Fix crash from Document `get_slice ()` on start up under some conditions

- src/MainWindow.vala
Fixes the dialog after git clone succeeded not being available for translation:
> MainWindow: Fix missing gettext

- plugins/markdown-actions/markdown-actions.vala
> Markdown: Fix hang when extending list on last line

- data/code.metainfo.xml.in
Pending merges with milestone = 8.1.0 (target date July 31)
> Prepare release 8.1.0
